### ISSUE TITLE
Change CSS of input element

### ISSUE THREAD

**Issue by sw-angel** [bleenco/ng2-datepicker#282]
I would like to edit the the appearance of the input element. I've already target the class but still the same. I also tried to target the input element and added a new css class to overwrite the styles  but still the same. 

Thanks

**Comment by jkuri** [comment]
did you use `!important` in your custom styles?

**Comment by aleksmudric** [comment]
Same issue here. Can you give an example how to change input appearance?

**Comment by jkuri** [comment]
something like
```css
.ngx-datepicker-container > .ngx-datepicker-input {
  border: 3px solid black !important;
}
```
should work.
